version: '3'
services:
  fishbase:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fishbase
    volumes:
      - ./mysql:/var/lib/mysql