# Generated by Django 4.0.4 on 2022-09-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation_name', models.CharField(max_length=70)),
                ('element', models.CharField(max_length=70)),
                ('kage_name', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(default='', max_length=70)),
                ('description', models.CharField(max_length=100)),
                ('nation_id', models.IntegerField(max_length=5)),
            ],
        ),
    ]
