# Generated by Django 4.0.4 on 2023-05-10 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shinobiAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='nation_id',
        ),
        migrations.AddField(
            model_name='village',
            name='element',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='village',
            name='kage_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='village',
            name='nation',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
