# Generated by Django 4.0.4 on 2023-05-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinobiAPI', '0002_remove_village_nation_id_village_element_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('salt', models.BinaryField()),
                ('hashed_password', models.BinaryField()),
            ],
        ),
    ]
